import { extractJsonLdEvents, extractTitleDateCandidates } from "@/lib/crawler/parsers";
import { fetchPublicHtml } from "@/lib/crawler/robots";
import type { CrawlSourceDefinition } from "@/lib/crawler/types";

function officialCalendarSource(
  definition: Omit<CrawlSourceDefinition, "crawl" | "robotsPolicy" | "parserType" | "confidence" | "crawlFrequency"> & {
    defaults: Parameters<typeof extractJsonLdEvents>[2];
    parserType?: "json-ld" | "html";
    confidence?: number;
    crawlFrequency?: "daily" | "weekly" | "monthly";
  },
): CrawlSourceDefinition {
  return {
    ...definition,
    robotsPolicy: "must-check",
    parserType: definition.parserType ?? "json-ld",
    confidence: definition.confidence ?? 80,
    crawlFrequency: definition.crawlFrequency ?? "daily",
    async crawl() {
      const { html } = await fetchPublicHtml(this.baseUrl);
      if (!html) return [];

      const jsonLd = extractJsonLdEvents(html, this, definition.defaults);
      if (jsonLd.length) return jsonLd;

      return extractTitleDateCandidates(html, this, definition.defaults);
    },
  };
}

export const officialCalendarSources: CrawlSourceDefinition[] = [
  officialCalendarSource({
    id: "gka-kite-world-tour",
    name: "GKA Kite World Tour",
    baseUrl: "https://www.gkakiteworldtour.com/events/",
    kind: "competition",
    termsNote: "Official public competition calendar. Crawl public pages only; do not bypass access controls.",
    defaults: {
      eventTypeSlug: "competition",
      organizerName: "GKA Kite World Tour",
      brandNames: ["Other"],
    },
    confidence: 92,
  }),
  officialCalendarSource({
    id: "formula-kite-calendar",
    name: "Formula Kite",
    baseUrl: "https://www.formulakite.org/events",
    kind: "competition",
    termsNote: "Official public class calendar. Verify extracted dates and locations in review.",
    defaults: {
      eventTypeSlug: "race",
      organizerName: "Formula Kite",
      brandNames: ["Other"],
    },
    confidence: 86,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "kitesurf-masters",
    name: "Kitesurf Masters",
    baseUrl: "https://www.kitesurf-masters.de/",
    kind: "competition",
    termsNote: "Official public event site. Verify partner and schedule details in review.",
    defaults: {
      eventTypeSlug: "competition",
      organizerName: "California Kitesurf Masters",
      country: "Germany",
      brandNames: ["Other"],
    },
    confidence: 82,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "lets-kite-agenda",
    name: "Let's Kite Agenda",
    baseUrl: "https://letskite.ch/en/agenda",
    kind: "event-platform",
    termsNote: "Public agenda source. Use as discovery only; all candidates stay pending admin review.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Let's Kite listed organizer",
      brandNames: ["Other"],
    },
    confidence: 72,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "world-sailing-calendar",
    name: "World Sailing Events",
    baseUrl: "https://www.sailing.org/events/",
    kind: "competition",
    termsNote: "Official public sailing federation events page. Use only public event listings and verify kite discipline relevance.",
    defaults: {
      eventTypeSlug: "race",
      organizerName: "World Sailing",
      brandNames: ["Other"],
    },
    confidence: 68,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "iqfoil-class-calendar",
    name: "iQFOiL Class Calendar",
    baseUrl: "https://www.iqfoilclassofficial.org/events",
    kind: "competition",
    termsNote: "Public class calendar for foil racing adjacency. Use as discovery and verify kite relevance in review.",
    defaults: {
      eventTypeSlug: "race",
      organizerName: "iQFOiL Class",
      brandNames: ["Other"],
    },
    confidence: 55,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "duotone-events",
    name: "Duotone Events",
    baseUrl: "https://www.duotonesports.com/events",
    kind: "brand",
    termsNote: "Public brand event page. Crawl only public listings and keep candidates pending review.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Duotone",
      brandNames: ["Duotone"],
    },
    confidence: 70,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "north-kiteboarding-events",
    name: "North Kiteboarding Events",
    baseUrl: "https://northkb.com/pages/events",
    kind: "brand",
    termsNote: "Public brand events page. Verify dates and event type before publishing.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "North Kiteboarding",
      brandNames: ["North"],
    },
    confidence: 68,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "core-kites-events",
    name: "CORE Kites Events",
    baseUrl: "https://corekites.com/events",
    kind: "brand",
    termsNote: "Public brand event page. Do not crawl private or gated content.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "CORE Kites",
      brandNames: ["Core"],
    },
    confidence: 66,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "cabrinha-events",
    name: "Cabrinha Events",
    baseUrl: "https://www.cabrinha.com/pages/events",
    kind: "brand",
    termsNote: "Public brand events page. Candidates must be reviewed before publishing.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Cabrinha",
      brandNames: ["Cabrinha"],
    },
    confidence: 66,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "fone-events",
    name: "F-One Events",
    baseUrl: "https://www.f-one.world/events/",
    kind: "brand",
    termsNote: "Public brand event page. Use respectful fetch cadence and review all candidates.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "F-One",
      brandNames: ["F-One"],
    },
    confidence: 64,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "flysurfer-events",
    name: "Flysurfer Events",
    baseUrl: "https://flysurfer.com/events/",
    kind: "brand",
    termsNote: "Public brand event page. Verify public availability and event details in admin review.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Flysurfer",
      brandNames: ["Flysurfer"],
    },
    confidence: 64,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "slingshot-events",
    name: "Slingshot Events",
    baseUrl: "https://slingshotsports.com/pages/events",
    kind: "brand",
    termsNote: "Public brand event page. Candidates stay pending until reviewed.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Slingshot Sports",
      brandNames: ["Slingshot"],
    },
    confidence: 62,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "naish-events",
    name: "Naish Events",
    baseUrl: "https://www.naish.com/pages/events",
    kind: "brand",
    termsNote: "Public brand event page. Verify before publishing.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Naish",
      brandNames: ["Naish"],
    },
    confidence: 60,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "airush-events",
    name: "Airush Events",
    baseUrl: "https://airush.com/pages/events",
    kind: "brand",
    termsNote: "Public brand event page. Verify public event details before publishing.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Airush",
      brandNames: ["Airush"],
    },
    confidence: 60,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "eleveight-events",
    name: "Eleveight Events",
    baseUrl: "https://www.eleveightkites.com/events/",
    kind: "brand",
    termsNote: "Public brand event page. Keep candidates in review until verified.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Eleveight",
      brandNames: ["Eleveight"],
    },
    confidence: 60,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "tarifa-events",
    name: "Tarifa Event Discovery",
    baseUrl: "https://www.turismotarifa.com/en/events/",
    kind: "tourism",
    termsNote: "Public tourism/event page for a major kite destination. Filter and verify kite relevance in review.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Tarifa listed organizer",
      country: "Spain",
      region: "Andalusia",
      city: "Tarifa",
      spotName: "Tarifa",
      latitude: 36.0143,
      longitude: -5.6044,
      brandNames: ["Other"],
    },
    confidence: 54,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "hood-river-events",
    name: "Hood River Event Discovery",
    baseUrl: "https://visithoodriver.com/events/",
    kind: "tourism",
    termsNote: "Public destination event calendar. Use as discovery only and verify kite relevance.",
    defaults: {
      eventTypeSlug: "community-meetup",
      organizerName: "Hood River listed organizer",
      country: "United States",
      region: "Oregon",
      city: "Hood River",
      spotName: "Columbia River Gorge",
      latitude: 45.7134,
      longitude: -121.5113,
      brandNames: ["Other"],
    },
    confidence: 52,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "dakhla-events",
    name: "Dakhla Event Discovery",
    baseUrl: "https://visitdakhla.com/",
    kind: "tourism",
    termsNote: "Public destination source for Dakhla. Verify event details and source pages before publishing.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Dakhla listed organizer",
      country: "Morocco",
      region: "Dakhla-Oued Ed-Dahab",
      city: "Dakhla",
      spotName: "Dakhla Lagoon",
      latitude: 23.6848,
      longitude: -15.9579,
      brandNames: ["Other"],
    },
    confidence: 50,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "cape-town-events",
    name: "Cape Town Event Discovery",
    baseUrl: "https://www.capetown.travel/events/",
    kind: "tourism",
    termsNote: "Public city event calendar. Use for discovery and verify kite relevance in review.",
    defaults: {
      eventTypeSlug: "community-meetup",
      organizerName: "Cape Town listed organizer",
      country: "South Africa",
      region: "Western Cape",
      city: "Cape Town",
      spotName: "Table View",
      latitude: -33.8222,
      longitude: 18.4772,
      brandNames: ["Other"],
    },
    confidence: 50,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "visit-fuerteventura-events",
    name: "Fuerteventura Event Discovery",
    baseUrl: "https://visitfuerteventura.com/en/events/",
    kind: "tourism",
    termsNote: "Public destination calendar. Verify kite relevance and location before publishing.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Fuerteventura listed organizer",
      country: "Spain",
      region: "Canary Islands",
      city: "Fuerteventura",
      spotName: "Sotavento",
      latitude: 28.1267,
      longitude: -14.268,
      brandNames: ["Other"],
    },
    confidence: 50,
    crawlFrequency: "monthly",
  }),
];
