import { extractJsonLdEvents, extractTitleDateCandidates } from "@/lib/crawler/parsers";
import { fetchPublicHtml } from "@/lib/crawler/robots";
import type { CrawlSourceDefinition } from "@/lib/crawler/types";

function officialCalendarSource(
  definition: Omit<CrawlSourceDefinition, "crawl" | "robotsPolicy" | "parserType" | "confidence" | "crawlFrequency"> & {
    defaults: Parameters<typeof extractJsonLdEvents>[2];
    parserType?: "json-ld" | "html";
    confidence?: number;
    crawlFrequency?: "daily" | "weekly" | "monthly";
  },
): CrawlSourceDefinition {
  return {
    ...definition,
    robotsPolicy: "must-check",
    parserType: definition.parserType ?? "json-ld",
    confidence: definition.confidence ?? 80,
    crawlFrequency: definition.crawlFrequency ?? "daily",
    async crawl() {
      const { html } = await fetchPublicHtml(this.baseUrl);
      if (!html) return [];

      const jsonLd = extractJsonLdEvents(html, this, definition.defaults);
      if (jsonLd.length) return jsonLd;

      return extractTitleDateCandidates(html, this, definition.defaults);
    },
  };
}

export const officialCalendarSources: CrawlSourceDefinition[] = [
  officialCalendarSource({
    id: "gka-kite-world-tour",
    name: "GKA Kite World Tour",
    baseUrl: "https://www.gkakiteworldtour.com/events/",
    kind: "competition",
    termsNote: "Official public competition calendar. Crawl public pages only; do not bypass access controls.",
    defaults: {
      eventTypeSlug: "competition",
      organizerName: "GKA Kite World Tour",
      brandNames: ["Other"],
    },
    confidence: 92,
  }),
  officialCalendarSource({
    id: "formula-kite-calendar",
    name: "Formula Kite",
    baseUrl: "https://www.formulakite.org/events",
    kind: "competition",
    termsNote: "Official public class calendar. Verify extracted dates and locations in review.",
    defaults: {
      eventTypeSlug: "race",
      organizerName: "Formula Kite",
      brandNames: ["Other"],
    },
    confidence: 86,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "kitesurf-masters",
    name: "Kitesurf Masters",
    baseUrl: "https://www.kitesurf-masters.de/",
    kind: "competition",
    termsNote: "Official public event site. Verify partner and schedule details in review.",
    defaults: {
      eventTypeSlug: "competition",
      organizerName: "California Kitesurf Masters",
      country: "Germany",
      brandNames: ["Other"],
    },
    confidence: 82,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "lets-kite-agenda",
    name: "LetsKite",
    baseUrl: "https://letskite.ch/en/agenda",
    kind: "event-platform",
    termsNote: "Public agenda source. Use as discovery only; all candidates stay pending admin review.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Let's Kite listed organizer",
      brandNames: ["Other"],
    },
    confidence: 72,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "international-kiteboarding-association",
    name: "International Kiteboarding Association",
    baseUrl: "https://www.kiteclasses.org/competitions/upcoming-events",
    kind: "competition",
    termsNote: "Official public competition calendar. Verify class, dates, and locations before publishing.",
    defaults: {
      eventTypeSlug: "competition",
      organizerName: "International Kiteboarding Association",
      brandNames: ["Other"],
    },
    confidence: 86,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "kiteworldshop-competition-calendar",
    name: "Kiteworldshop",
    baseUrl: "https://www.kiteworldshop.com/en/blog/calendar-competitions-kitesurfing-n18",
    kind: "event-platform",
    termsNote: "Public editorial competition calendar. Use as discovery and verify every event against its original source.",
    defaults: {
      eventTypeSlug: "competition",
      organizerName: "Kiteworldshop listed organizer",
      brandNames: ["Other"],
    },
    confidence: 60,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "rebels-tarifa-calendar",
    name: "Rebels Tarifa",
    baseUrl: "https://rebelstarifa.com/2025-calendar-kitesurfing-events-and-competitions/",
    kind: "event-platform",
    termsNote: "Public editorial kitesurfing calendar. Use as discovery and verify dates before publishing.",
    defaults: {
      eventTypeSlug: "competition",
      organizerName: "Rebels Tarifa listed organizer",
      country: "Spain",
      region: "Andalusia",
      city: "Tarifa",
      spotName: "Tarifa",
      latitude: 36.0143,
      longitude: -5.6044,
      brandNames: ["Other"],
    },
    confidence: 58,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "world-sailing-calendar",
    name: "World Sailing Events",
    baseUrl: "https://www.sailing.org/events/",
    kind: "competition",
    termsNote: "Official public sailing federation events page. Use only public event listings and verify kite discipline relevance.",
    defaults: {
      eventTypeSlug: "race",
      organizerName: "World Sailing",
      brandNames: ["Other"],
    },
    confidence: 68,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "iqfoil-class-calendar",
    name: "iQFOiL Class Calendar",
    baseUrl: "https://www.iqfoilclassofficial.org/events",
    kind: "competition",
    termsNote: "Public class calendar for foil racing adjacency. Use as discovery and verify kite relevance in review.",
    defaults: {
      eventTypeSlug: "race",
      organizerName: "iQFOiL Class",
      brandNames: ["Other"],
    },
    confidence: 55,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "duotone-events",
    name: "Duotone Events",
    baseUrl: "https://www.duotonesports.com/events",
    kind: "brand",
    termsNote: "Public brand event page. Crawl only public listings and keep candidates pending review.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Duotone",
      brandNames: ["Duotone"],
    },
    confidence: 70,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "duotone-pro-center",
    name: "Duotone Pro Center",
    baseUrl: "https://www.duotoneprocenter.com/",
    kind: "school",
    termsNote: "Public Duotone Pro Center network page. Use as school/network discovery and keep candidates pending review.",
    defaults: {
      eventTypeSlug: "training-camp",
      organizerName: "Duotone Pro Center",
      brandNames: ["Duotone"],
    },
    confidence: 55,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "ion-club",
    name: "ION Club",
    baseUrl: "https://www.ion-club.net/",
    kind: "school",
    termsNote: "Public watersports network site. Crawl public pages only and verify kite-specific relevance.",
    defaults: {
      eventTypeSlug: "training-camp",
      organizerName: "ION Club",
      brandNames: ["Other"],
    },
    confidence: 52,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "vdws",
    name: "VDWS",
    baseUrl: "https://www.vdws.de/",
    kind: "school",
    termsNote: "Public association site. Use as discovery for schools, camps, and public events only.",
    defaults: {
      eventTypeSlug: "training-camp",
      organizerName: "VDWS",
      brandNames: ["Other"],
    },
    confidence: 50,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "north-kiteboarding-events",
    name: "North Kiteboarding Events",
    baseUrl: "https://northkb.com/pages/events",
    kind: "brand",
    termsNote: "Public brand events page. Verify dates and event type before publishing.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "North Kiteboarding",
      brandNames: ["North"],
    },
    confidence: 68,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "core-kites-events",
    name: "CORE Kites Events",
    baseUrl: "https://corekites.com/events",
    kind: "brand",
    termsNote: "Public brand event page. Do not crawl private or gated content.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "CORE Kites",
      brandNames: ["Core"],
    },
    confidence: 66,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "cabrinha-events",
    name: "Cabrinha Events",
    baseUrl: "https://www.cabrinha.com/pages/events",
    kind: "brand",
    termsNote: "Public brand events page. Candidates must be reviewed before publishing.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Cabrinha",
      brandNames: ["Cabrinha"],
    },
    confidence: 66,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "fone-events",
    name: "F-One Events",
    baseUrl: "https://www.f-one.world/events/",
    kind: "brand",
    termsNote: "Public brand event page. Use respectful fetch cadence and review all candidates.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "F-One",
      brandNames: ["F-One"],
    },
    confidence: 64,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "flysurfer-events",
    name: "Flysurfer Events",
    baseUrl: "https://flysurfer.com/events/",
    kind: "brand",
    termsNote: "Public brand event page. Verify public availability and event details in admin review.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Flysurfer",
      brandNames: ["Flysurfer"],
    },
    confidence: 64,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "slingshot-events",
    name: "Slingshot Events",
    baseUrl: "https://slingshotsports.com/pages/events",
    kind: "brand",
    termsNote: "Public brand event page. Candidates stay pending until reviewed.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Slingshot Sports",
      brandNames: ["Slingshot"],
    },
    confidence: 62,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "naish-events",
    name: "Naish Events",
    baseUrl: "https://www.naish.com/pages/events",
    kind: "brand",
    termsNote: "Public brand event page. Verify before publishing.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Naish",
      brandNames: ["Naish"],
    },
    confidence: 60,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "airush-events",
    name: "Airush Events",
    baseUrl: "https://airush.com/pages/events",
    kind: "brand",
    termsNote: "Public brand event page. Verify public event details before publishing.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Airush",
      brandNames: ["Airush"],
    },
    confidence: 60,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "eleveight-events",
    name: "Eleveight Events",
    baseUrl: "https://www.eleveightkites.com/events/",
    kind: "brand",
    termsNote: "Public brand event page. Keep candidates in review until verified.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Eleveight",
      brandNames: ["Eleveight"],
    },
    confidence: 60,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "tarifa-events",
    name: "Tarifa Event Discovery",
    baseUrl: "https://www.turismotarifa.com/en/events/",
    kind: "tourism",
    termsNote: "Public tourism/event page for a major kite destination. Filter and verify kite relevance in review.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Tarifa listed organizer",
      country: "Spain",
      region: "Andalusia",
      city: "Tarifa",
      spotName: "Tarifa",
      latitude: 36.0143,
      longitude: -5.6044,
      brandNames: ["Other"],
    },
    confidence: 54,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "kitesurf-world-cup-sylt",
    name: "Kitesurf World Cup Sylt",
    baseUrl: "https://www.kitesurfworldcup.de/",
    kind: "competition",
    termsNote: "Official public event-specific site. Verify schedule and registration details before publishing.",
    defaults: {
      eventTypeSlug: "competition",
      organizerName: "Kitesurf World Cup Sylt",
      country: "Germany",
      region: "Schleswig-Holstein",
      city: "Sylt",
      spotName: "Westerland",
      latitude: 54.9079,
      longitude: 8.3033,
      brandNames: ["Other"],
    },
    confidence: 82,
    crawlFrequency: "weekly",
  }),
  officialCalendarSource({
    id: "defi-wind",
    name: "Defi Wind",
    baseUrl: "https://defiwind.com/",
    kind: "competition",
    termsNote: "Public event-specific site. Adjacent wind event source; verify kite relevance before publishing.",
    defaults: {
      eventTypeSlug: "race",
      organizerName: "Defi Wind",
      country: "France",
      region: "Occitanie",
      city: "Gruissan",
      spotName: "Gruissan",
      latitude: 43.1069,
      longitude: 3.0869,
      brandNames: ["Other"],
    },
    confidence: 45,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "tarifa-events-portal",
    name: "Tarifa Events Portal",
    baseUrl: "https://www.tarifa.com/",
    kind: "tourism",
    termsNote: "Public destination portal. Use as discovery and verify kite relevance before publishing.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Tarifa listed organizer",
      country: "Spain",
      region: "Andalusia",
      city: "Tarifa",
      spotName: "Tarifa",
      latitude: 36.0143,
      longitude: -5.6044,
      brandNames: ["Other"],
    },
    confidence: 48,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "duotone-kiteboarding-instagram",
    name: "Duotone Kiteboarding Instagram",
    baseUrl: "https://www.instagram.com/duotonekiteboarding/",
    kind: "brand",
    termsNote: "Public social profile only. Do not bypass logins, captchas, or anti-bot systems; use as low-confidence discovery.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "Duotone",
      brandNames: ["Duotone"],
    },
    confidence: 25,
    crawlFrequency: "monthly",
    parserType: "html",
  }),
  officialCalendarSource({
    id: "north-kiteboarding-instagram",
    name: "North Kiteboarding Instagram",
    baseUrl: "https://www.instagram.com/northkiteboarding/",
    kind: "brand",
    termsNote: "Public social profile only. Do not bypass logins, captchas, or anti-bot systems; use as low-confidence discovery.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "North Kiteboarding",
      brandNames: ["North"],
    },
    confidence: 25,
    crawlFrequency: "monthly",
    parserType: "html",
  }),
  officialCalendarSource({
    id: "fone-kites-instagram",
    name: "F-One Instagram",
    baseUrl: "https://www.instagram.com/fonekites/",
    kind: "brand",
    termsNote: "Public social profile only. Do not bypass logins, captchas, or anti-bot systems; use as low-confidence discovery.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "F-One",
      brandNames: ["F-One"],
    },
    confidence: 25,
    crawlFrequency: "monthly",
    parserType: "html",
  }),
  officialCalendarSource({
    id: "core-kiteboarding-instagram",
    name: "CORE Kiteboarding Instagram",
    baseUrl: "https://www.instagram.com/corekites/",
    kind: "brand",
    termsNote: "Public social profile only. Do not bypass logins, captchas, or anti-bot systems; use as low-confidence discovery.",
    defaults: {
      eventTypeSlug: "brand-activation",
      organizerName: "CORE Kiteboarding",
      brandNames: ["Core"],
    },
    confidence: 25,
    crawlFrequency: "monthly",
    parserType: "html",
  }),
  officialCalendarSource({
    id: "sylt-events",
    name: "Sylt",
    baseUrl: "https://www.sylt.de/",
    kind: "tourism",
    termsNote: "Public location portal. Use for destination discovery and verify kite relevance before publishing.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Sylt listed organizer",
      country: "Germany",
      region: "Schleswig-Holstein",
      city: "Sylt",
      spotName: "Westerland",
      latitude: 54.9079,
      longitude: 8.3033,
      brandNames: ["Other"],
    },
    confidence: 48,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "st-peter-ording-events",
    name: "St. Peter-Ording",
    baseUrl: "https://www.st-peter-ording.de/",
    kind: "tourism",
    termsNote: "Public location portal. Use for destination discovery and verify kite relevance before publishing.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "St. Peter-Ording listed organizer",
      country: "Germany",
      region: "Schleswig-Holstein",
      city: "St. Peter-Ording",
      spotName: "St. Peter-Ording",
      latitude: 54.3036,
      longitude: 8.6414,
      brandNames: ["Other"],
    },
    confidence: 48,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "el-gouna-events",
    name: "El Gouna",
    baseUrl: "https://elgouna.com/",
    kind: "tourism",
    termsNote: "Public location portal. Use for destination discovery and verify kite relevance before publishing.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "El Gouna listed organizer",
      country: "Egypt",
      region: "Red Sea",
      city: "El Gouna",
      spotName: "El Gouna",
      latitude: 27.3942,
      longitude: 33.6783,
      brandNames: ["Other"],
    },
    confidence: 48,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "dakhla-portal",
    name: "Dakhla",
    baseUrl: "https://dakhla.com/",
    kind: "tourism",
    termsNote: "Public location portal. Use for destination discovery and verify kite relevance before publishing.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Dakhla listed organizer",
      country: "Morocco",
      region: "Dakhla-Oued Ed-Dahab",
      city: "Dakhla",
      spotName: "Dakhla Lagoon",
      latitude: 23.6848,
      longitude: -15.9579,
      brandNames: ["Other"],
    },
    confidence: 48,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "jericoacoara-events",
    name: "Jericoacoara",
    baseUrl: "https://www.jericoacoara.com/",
    kind: "tourism",
    termsNote: "Public location portal. Use for destination discovery and verify kite relevance before publishing.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Jericoacoara listed organizer",
      country: "Brazil",
      region: "Ceara",
      city: "Jericoacoara",
      spotName: "Jericoacoara",
      latitude: -2.7956,
      longitude: -40.5142,
      brandNames: ["Other"],
    },
    confidence: 48,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "hood-river-events",
    name: "Hood River Event Discovery",
    baseUrl: "https://visithoodriver.com/events/",
    kind: "tourism",
    termsNote: "Public destination event calendar. Use as discovery only and verify kite relevance.",
    defaults: {
      eventTypeSlug: "community-meetup",
      organizerName: "Hood River listed organizer",
      country: "United States",
      region: "Oregon",
      city: "Hood River",
      spotName: "Columbia River Gorge",
      latitude: 45.7134,
      longitude: -121.5113,
      brandNames: ["Other"],
    },
    confidence: 52,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "dakhla-events",
    name: "Dakhla Event Discovery",
    baseUrl: "https://visitdakhla.com/",
    kind: "tourism",
    termsNote: "Public destination source for Dakhla. Verify event details and source pages before publishing.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Dakhla listed organizer",
      country: "Morocco",
      region: "Dakhla-Oued Ed-Dahab",
      city: "Dakhla",
      spotName: "Dakhla Lagoon",
      latitude: 23.6848,
      longitude: -15.9579,
      brandNames: ["Other"],
    },
    confidence: 50,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "cape-town-events",
    name: "Cape Town Event Discovery",
    baseUrl: "https://www.capetown.travel/events/",
    kind: "tourism",
    termsNote: "Public city event calendar. Use for discovery and verify kite relevance in review.",
    defaults: {
      eventTypeSlug: "community-meetup",
      organizerName: "Cape Town listed organizer",
      country: "South Africa",
      region: "Western Cape",
      city: "Cape Town",
      spotName: "Table View",
      latitude: -33.8222,
      longitude: 18.4772,
      brandNames: ["Other"],
    },
    confidence: 50,
    crawlFrequency: "monthly",
  }),
  officialCalendarSource({
    id: "visit-fuerteventura-events",
    name: "Fuerteventura Event Discovery",
    baseUrl: "https://visitfuerteventura.com/en/events/",
    kind: "tourism",
    termsNote: "Public destination calendar. Verify kite relevance and location before publishing.",
    defaults: {
      eventTypeSlug: "festival",
      organizerName: "Fuerteventura listed organizer",
      country: "Spain",
      region: "Canary Islands",
      city: "Fuerteventura",
      spotName: "Sotavento",
      latitude: 28.1267,
      longitude: -14.268,
      brandNames: ["Other"],
    },
    confidence: 50,
    crawlFrequency: "monthly",
  }),
];
